#!/bin/bash

set -e
bail() {
	echo >&2 $*
	exit 1
}

VERSION=$(perl -Ilib -MVerse -e 'print $Verse::VERSION' 2>/dev/null)
if [[ -z "$VERSION" ]]; then
	bail "Unable to determine Verse version from lib/Verse.pm!"
fi

if [[ -z $PERL5LIB ]]; then
	PERL5LIB=lib
else
	PERL5LIB=lib:$PERL5LIB
fi

echo "Packaging verse v$VERSION..."
./pack $VERSION
